### ISSUE TITLE
How do you do semantic segmentation visualisation?

### ISSUE THREAD

**Issue by hhhhsmx** [suyanfei/DLA-Net#3]

**Comment by hhhhsmx** [comment]
How did you do the semantic segmentation visualization? Can you share the source code or introduce a tutorial on how to use it?

**Comment by suyanfei** [comment]
When you get the final .ply files， which need to be computed the mIoU using the utils/6_fold_cv.py file.  During the calculation（in the utils/6_fold_cv.py file）, you can save the XYZ and Label value in a .txt file or .ply file and then convert the Label value to the corresponding RGB（for example 1 -> 255,255,0）.  Finally， you can visualize these files using the CloudCompare tool or mesh3D, or Open3D. I use the CloudCompare tool, which is easy to operate.
